// GENERATED by database/seeds/2026-10-09-as-kinematics-accelerated-motion.py — do not hand-edit.
// Each entry is the exact numbers used to build one question's figure; see KinematicsDiagrams.tsx
// for the reusable components that render them.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const KINEMATICS_DIAGRAM_DATA: Record<string, { kind: string; props: any }> = {
 "kin-1.1-q2": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 90,
     "dir": 1,
     "label": "90 km"
    }
   ],
   "unit": "km"
  }
 },
 "kin-1.1-q3": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 400,
     "dir": 1,
     "label": "400 m"
    }
   ],
   "unit": "m"
  }
 },
 "kin-1.1-q7": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 12,
     "dir": 1,
     "label": "12 km, 40 min"
    },
    {
     "distance": 8,
     "dir": 1,
     "label": "8 km, 20 min"
    }
   ],
   "unit": "km"
  }
 },
 "kin-1.1-q9": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 20
    },
    {
     "t": 30,
     "y": 50
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 30,
    "label": "distance = area"
   }
  }
 },
 "kin-1.1-q10": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 85.0,
     "dir": 1,
     "label": "85.0 m, shout"
    },
    {
     "distance": 85.0,
     "dir": -1,
     "label": "echo returns"
    }
   ],
   "unit": "m"
  }
 },
 "kin-1.1-q11": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 100,
     "dir": 1,
     "label": "100 m in 9.58 s"
    }
   ],
   "unit": "m"
  }
 },
 "kin-1.1-q12": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 5.0,
     "dir": 1,
     "label": "5.0 m"
    }
   ],
   "unit": "m"
  }
 },
 "kin-1.1-q14": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 4.0,
     "dir": 1,
     "label": "4.0 km @ 8.0 km/h"
    },
    {
     "distance": 4.0,
     "dir": -1,
     "label": "4.0 km @ 12 km/h"
    }
   ],
   "unit": "km"
  }
 },
 "kin-1.1-q15": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 30,
     "dir": 1,
     "label": "30 km @ 90 km/h"
    },
    {
     "distance": 15,
     "dir": 1,
     "label": "15 km @ 30 km/h"
    }
   ],
   "unit": "km"
  }
 },
 "kin-1.1-q16": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 560,
     "dir": 1,
     "label": "560 km @ 306 m/s"
    },
    {
     "distance": 5000,
     "dir": 1,
     "label": "5000 km @ 680 m/s"
    }
   ],
   "unit": "km"
  }
 },
 "kin-1.1-q17": {
  "kind": "table",
  "props": {
   "headers": [
    "Stage",
    "Hare",
    "Tortoise"
   ],
   "rows": [
    [
     "Leg 1",
     "100 m @ 8.0 m/s",
     "1000 m @ 0.60 m/s"
    ],
    [
     "Pause",
     "1800 s nap",
     "—"
    ],
    [
     "Leg 2",
     "900 m @ 10 m/s",
     "—"
    ],
    [
     "Total time",
     "1900 s",
     "1670 s"
    ]
   ]
  }
 },
 "kin-1.1-q18": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 18.0,
     "dir": 1,
     "label": "18.0 km, 24 min"
    },
    {
     "distance": 14.0,
     "dir": 1,
     "label": "14.0 km, 36 min"
    }
   ],
   "unit": "km"
  }
 },
 "kin-1.1-q19": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 50,
     "dir": 1,
     "label": "d @ v₁ = 40 km/h"
    },
    {
     "distance": 50,
     "dir": 1,
     "label": "d @ v₂ = 60 km/h"
    }
   ],
   "unit": ""
  }
 },
 "kin-1.2-q2": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 300,
     "dir": 1,
     "label": "300 m east"
    },
    {
     "distance": 300,
     "dir": -1,
     "label": "300 m west"
    }
   ],
   "unit": "m"
  }
 },
 "kin-1.2-q5": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 8,
     "dir": 1,
     "label": "8 m east"
    },
    {
     "distance": 6,
     "dir": 1,
     "label": "6 m east"
    }
   ],
   "unit": "m"
  }
 },
 "kin-1.2-q6": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 4.0,
     "dir": 1,
     "label": "4.0 m N"
    },
    {
     "distance": 3.0,
     "dir": 1,
     "label": "3.0 m N"
    },
    {
     "distance": 2.0,
     "dir": -1,
     "label": "2.0 m S"
    }
   ],
   "unit": "m"
  }
 },
 "kin-1.2-q7": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 300,
     "angleDeg": 0,
     "label": "300 m E"
    },
    {
     "magnitude": 400,
     "angleDeg": 90,
     "label": "400 m N"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.2-q9": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 3.0,
     "dir": 1,
     "label": "3.0 km E"
    },
    {
     "distance": 4.0,
     "dir": 1,
     "label": "4.0 km E"
    },
    {
     "distance": 2.0,
     "dir": -1,
     "label": "2.0 km W"
    }
   ],
   "unit": "km"
  }
 },
 "kin-1.2-q11": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 8.0,
     "angleDeg": 0,
     "label": "8.0 m"
    },
    {
     "magnitude": 8.0,
     "angleDeg": 90,
     "label": "8.0 m"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "displacement"
   }
  }
 },
 "kin-1.2-q12": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 40,
     "angleDeg": 270,
     "label": "40 km S"
    },
    {
     "magnitude": 30,
     "angleDeg": 180,
     "label": "30 km W"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   },
   "compass": true
  }
 },
 "kin-1.2-q14": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 6.0,
     "angleDeg": 0,
     "label": "6.0 m"
    },
    {
     "magnitude": 8.0,
     "angleDeg": 90,
     "label": "8.0 m"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "diagonal, 10 m"
   }
  }
 },
 "kin-1.2-q15": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 5.0,
     "angleDeg": 0,
     "label": "5.0 km E"
    },
    {
     "magnitude": 12.0,
     "angleDeg": 90,
     "label": "X (north)"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "13.0 km"
   }
  }
 },
 "kin-1.2-q16": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 300,
     "angleDeg": 90,
     "label": "300 m N"
    },
    {
     "magnitude": 400,
     "angleDeg": 0,
     "label": "400 m E"
    },
    {
     "magnitude": 100,
     "angleDeg": 270,
     "label": "100 m S"
    },
    {
     "magnitude": 100,
     "angleDeg": 180,
     "label": "100 m W"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.2-q18": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 2.0,
     "angleDeg": 90,
     "label": "2.0 km N"
    },
    {
     "magnitude": 2.0,
     "angleDeg": 0,
     "label": "2.0 km E"
    },
    {
     "magnitude": 2.0,
     "angleDeg": 270,
     "label": "2.0 km S"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "displacement"
   }
  }
 },
 "kin-1.2-q19": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 40,
     "angleDeg": 0,
     "label": "+40 cm"
    },
    {
     "magnitude": 30,
     "angleDeg": 90,
     "label": "+30 cm"
    },
    {
     "magnitude": 40,
     "angleDeg": 180,
     "label": "−40 cm"
    },
    {
     "magnitude": 10,
     "angleDeg": 270,
     "label": "−10 cm"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "net displacement"
   }
  }
 },
 "kin-1.3-q3": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": -15
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q6": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 8.0,
     "y": -40
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q7": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 10,
     "y": 40
    },
    {
     "t": 15,
     "y": 30
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q9": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 40,
     "y": 50
    },
    {
     "t": 80,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q10": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 12
    },
    {
     "t": 5.0,
     "y": -8
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q12": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 9.0,
     "y": -18
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q13": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 60,
     "y": 300
    },
    {
     "t": 100,
     "y": 200
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q14": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 10,
     "y": 15
    },
    {
     "t": 30,
     "y": 15
    },
    {
     "t": 36,
     "y": 6
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q15": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 8.0
    },
    {
     "t": 4.0,
     "y": 8.0
    },
    {
     "t": 4.0,
     "y": -2.0
    },
    {
     "t": 10.0,
     "y": -2.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ]
  }
 },
 "kin-1.3-q16": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": 120
    },
    {
     "t": 8.0,
     "y": 150
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.3-q17": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "5",
    "10",
    "15",
    "20"
   ],
   "rows": [
    [
     "x / m",
     "0",
     "8",
     "20",
     "20",
     "36"
    ]
   ]
  }
 },
 "kin-1.3-q18": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 2.0,
     "y": 1800.0
    },
    {
     "t": 3.5,
     "y": 2772.0
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "h",
   "yUnit": "km"
  }
 },
 "kin-1.3-q19": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 12.4
    },
    {
     "t": 0.1,
     "y": 11.8
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m",
   "markers": [
    {
     "t": 0,
     "y": 12.4,
     "label": "t"
    },
    {
     "t": 0.1,
     "y": 11.8,
     "label": "t+0.10s"
    }
   ]
  }
 },
 "kin-1.4-q2": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 8
    },
    {
     "t": 10,
     "y": 8
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.4-q3": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": 20
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.4-q5": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 4.0,
     "y": -6
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.4-q6": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 6.0,
     "y": 24
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m",
   "markers": [
    {
     "t": 3.0,
     "y": 12,
     "label": "t=3.0s"
    }
   ]
  }
 },
 "kin-1.4-q7": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 4,
     "y": 8
    },
    {
     "t": 9,
     "y": 8
    },
    {
     "t": 12,
     "y": 2
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.4-q9": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 5.0
    },
    {
     "t": 10,
     "y": 35
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m",
   "markers": [
    {
     "t": 4.0,
     "y": 17,
     "label": "t=4.0s"
    }
   ]
  }
 },
 "kin-1.4-q10": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 6,
     "y": 18
    },
    {
     "t": 10,
     "y": 18
    },
    {
     "t": 14,
     "y": 2
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m",
   "markers": [
    {
     "t": 3.0,
     "y": 9,
     "label": "A"
    },
    {
     "t": 12,
     "y": 10.0,
     "label": "B"
    }
   ]
  }
 },
 "kin-1.4-q12": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0,
     "slopeIn": 0
    },
    {
     "t": 10,
     "y": 40
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m",
   "curved": true,
   "tangentAt": 5.0
  }
 },
 "kin-1.4-q13": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 6,
     "y": 18
    },
    {
     "t": 12,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.4-q14": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 4,
     "y": 20
    },
    {
     "t": 7,
     "y": 20
    },
    {
     "t": 10,
     "y": -10
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.4-q15": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 10,
     "y": 15
    },
    {
     "t": 25,
     "y": 15
    },
    {
     "t": 40,
     "y": -5
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "min",
   "yUnit": "km"
  }
 },
 "kin-1.4-q16": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5,
     "y": 10
    },
    {
     "t": 10,
     "y": -10
    },
    {
     "t": 15,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.4-q18": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0,
     "slopeIn": 0
    },
    {
     "t": 5.0,
     "y": 25,
     "slopeIn": 10
    },
    {
     "t": 9.0,
     "y": 65
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m",
   "curved": true
  }
 },
 "kin-1.4-q19": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0,
     "slopeIn": 0
    },
    {
     "t": 8,
     "y": 48.0
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m",
   "curved": true,
   "tangentAt": 2.0
  }
 },
 "kin-1.4-q20": {
  "kind": "motion",
  "props": {
   "kind": "displacement",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 0.4,
     "y": 0.024
    },
    {
     "t": 0.5,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "displacement",
   "xUnit": "s",
   "yUnit": "m"
  }
 },
 "kin-1.5-q2": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 6.0,
     "angleDeg": 0,
     "label": "6.0 m"
    },
    {
     "magnitude": 4.0,
     "angleDeg": 0,
     "label": "4.0 m"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.5-q3": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 6.0,
     "angleDeg": 0,
     "label": "6.0 m E"
    },
    {
     "magnitude": 8.0,
     "angleDeg": 90,
     "label": "8.0 m N"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.5-q4": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 10,
     "angleDeg": 30,
     "label": "10 m"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.5-q5": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 10,
     "angleDeg": 30,
     "label": "10 m"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.5-q7": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 50,
     "angleDeg": 0,
     "label": "50 m"
    },
    {
     "magnitude": 50,
     "angleDeg": 60,
     "label": "50 m"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.5-q9": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 25,
     "angleDeg": 150,
     "label": "25 m"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.5-q10": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 10,
     "angleDeg": 0,
     "label": "(10,0)"
    },
    {
     "magnitude": 15,
     "angleDeg": 90,
     "label": "(0,15)"
    },
    {
     "magnitude": 5,
     "angleDeg": 143.13010235415598,
     "label": "(−4,3)"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.5-q12": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 10,
     "angleDeg": 36.86989764584402,
     "label": "(8,6)"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.5-q13": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 120,
     "angleDeg": 0,
     "label": "120 m E"
    },
    {
     "magnitude": 50,
     "angleDeg": 90,
     "label": "50 m N"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   },
   "compass": true
  }
 },
 "kin-1.5-q14": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 8.0,
     "angleDeg": 30,
     "label": "8.0 km, 060°"
    },
    {
     "magnitude": 5.0,
     "angleDeg": -60,
     "label": "5.0 km, 150°"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   },
   "compass": true
  }
 },
 "kin-1.5-q15": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 15,
     "angleDeg": 0,
     "label": "A = 15 m"
    },
    {
     "magnitude": 15.811388300841896,
     "angleDeg": 71.56505117707799,
     "label": "B = ?",
     "dashed": true
    }
   ],
   "mode": "fromOrigin",
   "resultant": {
    "label": "R = 25 m, 36.9°"
   }
  }
 },
 "kin-1.5-q16": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 300,
     "angleDeg": 0,
     "label": "300 m E"
    },
    {
     "magnitude": 400,
     "angleDeg": 60,
     "label": "400 m, 030°"
    },
    {
     "magnitude": 200,
     "angleDeg": 270,
     "label": "200 m S"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   },
   "compass": true
  }
 },
 "kin-1.5-q17": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 200,
     "angleDeg": 0,
     "label": "200 m E"
    },
    {
     "magnitude": 150,
     "angleDeg": 90,
     "label": "150 m N"
    },
    {
     "magnitude": 100,
     "angleDeg": -110,
     "label": "100 m, 200°"
    }
   ],
   "mode": "tipToTail",
   "resultant": null
  }
 },
 "kin-1.5-q18": {
  "kind": "table",
  "props": {
   "headers": [
    "Leg",
    "Magnitude",
    "Bearing"
   ],
   "rows": [
    [
     "1",
     "10 m",
     "000°"
    ],
    [
     "2",
     "10 m",
     "120°"
    ],
    [
     "3",
     "10 m",
     "240°"
    ]
   ]
  }
 },
 "kin-1.5-q19": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 10,
     "angleDeg": 40,
     "label": "A"
    },
    {
     "magnitude": 10,
     "angleDeg": -40,
     "label": "A"
    }
   ],
   "mode": "fromOrigin",
   "resultant": {
    "label": "R"
   }
  }
 },
 "kin-1.5-q20": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 1.4422205101855956,
     "angleDeg": 33.69006752597979,
     "label": "Hr 1"
    },
    {
     "magnitude": 1.5811388300841898,
     "angleDeg": -71.56505117707799,
     "label": "Hr 2"
    },
    {
     "magnitude": 0.9486832980505138,
     "angleDeg": 161.565051177078,
     "label": "Hr 3"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "net"
   },
   "compass": true
  }
 },
 "kin-1.6-q2": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 5.0,
     "angleDeg": 0,
     "label": "swimmer, 5.0 m/s"
    },
    {
     "magnitude": 2.0,
     "angleDeg": 0,
     "label": "current, 2.0 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.6-q3": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 2.0,
     "angleDeg": 0,
     "label": "swimmer, +2.0 m/s"
    },
    {
     "magnitude": 3.0,
     "angleDeg": 180,
     "label": "current, −3.0 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.6-q4": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 3.0,
     "angleDeg": 90,
     "label": "boat, 3.0 m/s"
    },
    {
     "magnitude": 4.0,
     "angleDeg": 0,
     "label": "current, 4.0 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.6-q5": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 20,
     "angleDeg": 150,
     "label": "wind, 20 m/s"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.6-q7": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 2.0,
     "angleDeg": 90,
     "label": "boat, 2.0 m/s"
    },
    {
     "magnitude": 1.5,
     "angleDeg": 0,
     "label": "current, 1.5 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.6-q9": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 5.0,
     "angleDeg": 126.86989764584402,
     "label": "boat, 5.0 m/s"
    },
    {
     "magnitude": 3.0,
     "angleDeg": 0,
     "label": "current, 3.0 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "straight across"
   }
  }
 },
 "kin-1.6-q10": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 300,
     "angleDeg": 90,
     "label": "airspeed, 300 km/h"
    },
    {
     "magnitude": 60,
     "angleDeg": 0,
     "label": "wind, 60 km/h"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "ground track"
   },
   "compass": true
  }
 },
 "kin-1.6-q12": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 1.2,
     "angleDeg": 90,
     "label": "swimmer, 1.2 m/s"
    },
    {
     "magnitude": 0.8,
     "angleDeg": 0,
     "label": "current, 0.80 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.6-q14": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 2.0,
     "angleDeg": 90,
     "label": "boat, 2.0 m/s"
    },
    {
     "magnitude": 1.5,
     "angleDeg": 0,
     "label": "current, 1.5 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant, 2.5 m/s"
   }
  }
 },
 "kin-1.6-q15": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 4.0,
     "angleDeg": 126.86989764584402,
     "label": "boat, 4.0 m/s"
    },
    {
     "magnitude": 2.4,
     "angleDeg": 0,
     "label": "current, 2.4 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "straight across"
   }
  }
 },
 "kin-1.6-q16": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 250,
     "angleDeg": 99.2068962213459,
     "label": "airspeed, 250 km/h"
    },
    {
     "magnitude": 40,
     "angleDeg": 0,
     "label": "wind, 40 km/h"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "ground track, due N"
   },
   "compass": true
  }
 },
 "kin-1.6-q18": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 8.0,
     "angleDeg": 270,
     "label": "rain, 8.0 m/s"
    },
    {
     "magnitude": 6.0,
     "angleDeg": 180,
     "label": "−cyclist, 6.0 m/s"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "rain rel. to cyclist"
   }
  }
 },
 "kin-1.7-q3": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 5.0,
     "angleDeg": 180,
     "label": "−v₁"
    },
    {
     "magnitude": 3.0,
     "angleDeg": 180,
     "label": "v₂"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "Δv"
   }
  }
 },
 "kin-1.7-q5": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 10,
     "angleDeg": 0,
     "label": "A = 10 m"
    },
    {
     "magnitude": 6,
     "angleDeg": 180,
     "label": "−B"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "A−B"
   }
  }
 },
 "kin-1.7-q7": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 6.0,
     "angleDeg": 180,
     "label": "−v₁"
    },
    {
     "magnitude": 6.0,
     "angleDeg": 90,
     "label": "v₂"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "Δv"
   }
  }
 },
 "kin-1.7-q9": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 8.0,
     "angleDeg": 180,
     "label": "−v₁"
    },
    {
     "magnitude": 8.0,
     "angleDeg": 90,
     "label": "v₂"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "Δv"
   }
  }
 },
 "kin-1.7-q12": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 5.0,
     "angleDeg": 216.86989764584402,
     "label": "−v₁"
    },
    {
     "magnitude": 7.0710678118654755,
     "angleDeg": 81.86989764584403,
     "label": "v₂"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "Δv"
   }
  }
 },
 "kin-1.7-q13": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 6.0,
     "angleDeg": 180,
     "label": "−v₁"
    },
    {
     "magnitude": 6.0,
     "angleDeg": 180,
     "label": "v₂"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "Δv"
   }
  }
 },
 "kin-1.7-q14": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 15,
     "angleDeg": 180,
     "label": "−v₁"
    },
    {
     "magnitude": 15,
     "angleDeg": 90,
     "label": "v₂"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "Δv"
   }
  }
 },
 "kin-1.7-q16": {
  "kind": "table",
  "props": {
   "headers": [
    "",
    "vx / m/s",
    "vy / m/s"
   ],
   "rows": [
    [
     "before",
     "8.0",
     "−6.0"
    ],
    [
     "after",
     "8.0",
     "+4.0"
    ]
   ]
  }
 },
 "kin-1.7-q17": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "vx / m/s",
    "vy / m/s"
   ],
   "rows": [
    [
     "0",
     "5.0",
     "0"
    ],
    [
     "4.0",
     "5.0",
     "12"
    ]
   ]
  }
 },
 "kin-1.7-q18": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 20,
     "angleDeg": 0,
     "label": "vₐ"
    },
    {
     "magnitude": 20.0,
     "angleDeg": 233.13010235415598,
     "label": "−v_B"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "vₐ−v_B"
   }
  }
 },
 "kin-1.8-q5": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 49.050000000000004,
     "angleDeg": 270,
     "label": "weight = 49.1 N"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.8-q7": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 50,
     "angleDeg": 40,
     "label": "50 N"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.8-q9": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 12.0,
     "angleDeg": 0,
     "label": "p = 12.0 kg m/s"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.8-q10": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 30,
     "angleDeg": 0,
     "label": "30 N E"
    },
    {
     "magnitude": 40,
     "angleDeg": 90,
     "label": "40 N N"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   },
   "compass": true
  }
 },
 "kin-1.8-q12": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 20,
     "angleDeg": 270,
     "label": "weight, 20 N"
    },
    {
     "magnitude": 25,
     "angleDeg": 60,
     "label": "tension, 25 N"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.8-q14": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 80,
     "angleDeg": 0,
     "label": "80 N"
    },
    {
     "magnitude": 60,
     "angleDeg": 90,
     "label": "60 N"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.8-q15": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 30,
     "angleDeg": 270,
     "label": "weight, 30 N"
    },
    {
     "magnitude": 45,
     "angleDeg": 70,
     "label": "lift, 45 N"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-1.8-q17": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 2.0,
     "angleDeg": 180,
     "label": "−pᵢ"
    },
    {
     "magnitude": 2.0,
     "angleDeg": 180,
     "label": "p_f"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "Δp"
   }
  }
 },
 "kin-1.8-q18": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 500,
     "angleDeg": 0,
     "label": "500 N/C"
    },
    {
     "magnitude": 300,
     "angleDeg": 90,
     "label": "300 N/C"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-1.8-q19": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 120,
     "angleDeg": 0,
     "label": "120 N"
    },
    {
     "magnitude": 96.5525765980214,
     "angleDeg": 93.02386577889136,
     "label": "F = ?",
     "dashed": true
    }
   ],
   "mode": "fromOrigin",
   "resultant": {
    "label": "R = 150 N, 40°"
   }
  }
 },
 "kin-1.8-q20": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 6,
     "angleDeg": 0,
     "label": "(6,0)"
    },
    {
     "magnitude": 8,
     "angleDeg": 90,
     "label": "(0,8)"
    },
    {
     "magnitude": 2.23606797749979,
     "angleDeg": 206.56505117707798,
     "label": "(−2,−1)"
    }
   ],
   "mode": "tipToTail",
   "resultant": {
    "label": "resultant"
   }
  }
 },
 "kin-2.1-q3": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 3.0,
     "y": 16
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.1-f6": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 20
    },
    {
     "t": 6,
     "y": 20
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.1-q7": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 5
    },
    {
     "t": 2.0,
     "y": -3
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ]
  }
 },
 "kin-2.1-q9": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 40
    },
    {
     "t": 20,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.1-q11": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 1.5,
     "y": 3.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.1-q13": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 4.0
    },
    {
     "t": 12,
     "y": 10
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.1-q14": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 2.0,
     "y": 10
    },
    {
     "t": 8.0,
     "y": 10
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.1-q15": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 15
    },
    {
     "t": 1.529051987767584,
     "y": 0
    },
    {
     "t": 3.058103975535168,
     "y": -15
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ],
   "markers": [
    {
     "t": 0.5,
     "y": 10.094999999999999,
     "label": "t=0.5s"
    }
   ]
  }
 },
 "kin-2.1-q16": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "3",
     "6",
     "9",
     "12",
     "16"
    ]
   ]
  }
 },
 "kin-2.1-q18": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 4.0,
     "y": 8.0
    },
    {
     "t": 14.0,
     "y": 8.0
    },
    {
     "t": 16.0,
     "y": 0.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-f1": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 10,
     "y": 27.77777777777778
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-f2": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 400
    },
    {
     "t": 0.02,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "speed",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-f4": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 5.0
    },
    {
     "t": 4.0,
     "y": 17
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-f5": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": 30
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-f6": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 30
    },
    {
     "t": 5.0,
     "y": 20
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-q7": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 15,
     "y": 12.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-q9": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 3.0,
     "y": 6.0
    },
    {
     "t": 7.0,
     "y": 2.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-q10": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 27.77777777777778
    },
    {
     "t": 2.5,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "speed",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-q12": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0.0
    },
    {
     "t": 6.0,
     "y": 15
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-q13": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 2.0,
     "y": 2.4
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-q14": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": 100.0
    },
    {
     "t": 15.0,
     "y": 200.0
    },
    {
     "t": 35.0,
     "y": 300.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-q15": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 30
    },
    {
     "t": 4.0,
     "y": 10
    },
    {
     "t": 9.0,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.2-q16": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "2.2",
    "4.1",
    "6.0"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "45",
     "89",
     "130"
    ]
   ]
  }
 },
 "kin-2.2-q18": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 5.0
    },
    {
     "t": 4.0,
     "y": 25
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.3-q14": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 88.29,
     "angleDeg": 0,
     "label": "88.3 m/s² (9.0g)"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-2.3-q16": {
  "kind": "table",
  "props": {
   "headers": [
    "Row",
    "Value",
    "Unit"
   ],
   "rows": [
    [
     "A",
     "3.5",
     "g"
    ],
    [
     "B",
     "40",
     "m/s²"
    ],
    [
     "C",
     "3600",
     "km/h²"
    ]
   ]
  }
 },
 "kin-2.4-q2": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": 20
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q3": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 12
    },
    {
     "t": 10,
     "y": 12
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q5": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 15
    },
    {
     "t": 3.0,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q6": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 5.0
    },
    {
     "t": 10,
     "y": 25
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q7": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 4,
     "y": 8
    },
    {
     "t": 9,
     "y": 8
    },
    {
     "t": 12,
     "y": 2
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q9": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 6.0,
     "y": 40
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q10": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 30
    },
    {
     "t": 5.0,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q12": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 5.8,
     "y": 16.82
    },
    {
     "t": 6.2,
     "y": 19.220000000000002
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q13": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "1",
    "2",
    "3",
    "4"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "4",
     "9",
     "16",
     "25"
    ]
   ]
  }
 },
 "kin-2.4-q14": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5,
     "y": 20
    },
    {
     "t": 15,
     "y": 20
    },
    {
     "t": 20,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q17": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 2.0
    },
    {
     "t": 10,
     "y": 22
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.4-q18": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 12
    },
    {
     "t": 8.0,
     "y": -4
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ]
  }
 },
 "kin-2.5-q2": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 5.0,
     "y": 10
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 5.0,
    "label": "area = displacement"
   }
  }
 },
 "kin-2.5-q3": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 4.0,
     "y": 20
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 4.0,
    "label": "area = displacement"
   }
  }
 },
 "kin-2.5-q5": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 6.0
    },
    {
     "t": 8.0,
     "y": 6.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 8.0,
    "label": ""
   }
  }
 },
 "kin-2.5-q6": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 12
    },
    {
     "t": 6.0,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 6.0,
    "label": "area = displacement"
   }
  }
 },
 "kin-2.5-q7": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 5.0
    },
    {
     "t": 4.0,
     "y": 15
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 4.0,
    "label": "area = displacement"
   }
  }
 },
 "kin-2.5-q9": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 2.0,
     "y": 10
    },
    {
     "t": 8.0,
     "y": 10
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 8.0,
    "label": "area = displacement"
   }
  }
 },
 "kin-2.5-q10": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 20
    },
    {
     "t": 3.0,
     "y": 5
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 3.0,
    "label": "area = displacement"
   }
  }
 },
 "kin-2.5-q12": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": -4.0
    },
    {
     "t": 5.0,
     "y": -4.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "yMin": -5,
   "shade": {
    "t0": 0,
    "t1": 5.0,
    "label": ""
   },
   "hRefLines": [
    0
   ]
  }
 },
 "kin-2.5-q13": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 6.0,
     "y": -5
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ]
  }
 },
 "kin-2.5-q14": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5,
     "y": 20
    },
    {
     "t": 15,
     "y": 20
    },
    {
     "t": 20,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 20,
    "label": ""
   }
  }
 },
 "kin-2.5-q15": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 8.0
    },
    {
     "t": 6.0,
     "y": -4.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ]
  }
 },
 "kin-2.5-q16": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "2",
    "4",
    "6",
    "8",
    "10"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "4",
     "7",
     "9",
     "10",
     "10"
    ]
   ]
  }
 },
 "kin-2.5-q17": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 15
    },
    {
     "t": 12,
     "y": -9
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ]
  }
 },
 "kin-2.6-q2": {
  "kind": "ticker",
  "props": {
   "gaps": [
    3.0,
    3.0,
    3.0,
    3.0
   ],
   "unit": "cm",
   "intervalLabel": "0.020 s between dots"
  }
 },
 "kin-2.6-q6": {
  "kind": "ticker",
  "props": {
   "gaps": [
    4.5,
    4.5,
    4.5
   ],
   "unit": "cm",
   "intervalLabel": "0.020 s between dots"
  }
 },
 "kin-2.6-q9": {
  "kind": "lightgate",
  "props": {
   "gateDistanceCm": 50,
   "cardLengthCm": 5.0
  }
 },
 "kin-2.6-q13": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 0.6,
     "dir": 1,
     "label": "0.600 m in 0.040 s"
    }
   ],
   "unit": "m"
  }
 },
 "kin-2.6-q15": {
  "kind": "ticker",
  "props": {
   "gaps": [
    1.0,
    1.4,
    1.8,
    2.2
   ],
   "unit": "cm",
   "intervalLabel": "0.020 s between dots"
  }
 },
 "kin-2.6-q17": {
  "kind": "path",
  "props": {
   "legs": [
    {
     "distance": 0.06,
     "dir": 1,
     "label": "0.060 m in 0.20 s"
    }
   ],
   "unit": "m"
  }
 },
 "kin-2.6-q18": {
  "kind": "balldrop",
  "props": {
   "heights": [
    0.3
   ]
  }
 },
 "kin-2.7-q7": {
  "kind": "table",
  "props": {
   "headers": [
    "Reading",
    "1",
    "2",
    "3",
    "4",
    "5"
   ],
   "rows": [
    [
     "t / s",
     "0.42",
     "0.44",
     "0.41",
     "0.45",
     "0.43"
    ]
   ]
  }
 },
 "kin-2.7-q14": {
  "kind": "lightgate",
  "props": {
   "gateDistanceCm": 60.0,
   "cardLengthCm": 5.0
  }
 },
 "kin-2.7-q17": {
  "kind": "balldrop",
  "props": {
   "heights": [
    1.2
   ]
  }
 },
 "kin-2.7-q19": {
  "kind": "lightgate",
  "props": {
   "gateDistanceCm": 50,
   "cardLengthCm": 5.0
  }
 },
 "kin-2.8-f2": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 5.0
    },
    {
     "t": 4.0,
     "y": 13
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.8-f3": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": 15
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 5.0,
    "label": "s = 37.5 m"
   }
  }
 },
 "kin-2.8-f5": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 6.0,
     "y": 20
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 6.0,
    "label": "s = 90.0 m"
   }
  }
 },
 "kin-2.8-q7": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 13
    },
    {
     "t": 4.0,
     "y": 25
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.8-q8": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 5.0,
     "y": 30
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.8-q9": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 6.0
    },
    {
     "t": 4.0,
     "y": 18
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.8-q12": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 20
    },
    {
     "t": 3.0,
     "y": 8
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.8-q13": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 15
    },
    {
     "t": 2.0,
     "y": 9
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 2.0,
    "label": "s = 24.0 m"
   }
  }
 },
 "kin-2.8-q14": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 5.0
    },
    {
     "t": 6.0,
     "y": 17
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 6.0,
    "label": "s = 66.0 m"
   }
  }
 },
 "kin-2.8-q15": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 25
    },
    {
     "t": 5.0,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 5.0,
    "label": "s = 62.5 m"
   }
  }
 },
 "kin-2.8-q16": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 4.0,
     "y": 12.0
    },
    {
     "t": 9.0,
     "y": 12.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 9.0,
    "label": ""
   }
  }
 },
 "kin-2.8-q18": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": 40.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 5.0,
    "label": "s = 100 m"
   }
  }
 },
 "kin-2.9-f2": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 4.0
    },
    {
     "t": 3.0,
     "y": 10
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.9-f4": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 4.0
    },
    {
     "t": 3.0,
     "y": 10
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 3.0,
    "label": "s = 21.0 m"
   }
  }
 },
 "kin-2.9-f6": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 4.0
    },
    {
     "t": 3.0,
     "y": 10
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 3.0,
    "label": "s = 21.0 m"
   }
  }
 },
 "kin-2.9-q7": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 6
    },
    {
     "t": 2.0,
     "y": 14
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 2.0,
    "label": "s = 20.0 m"
   }
  }
 },
 "kin-2.9-q9": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 3.0
    },
    {
     "t": 2.0,
     "y": 13
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 2.0,
    "label": "s = 16.0 m"
   }
  }
 },
 "kin-2.9-q11": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 8.0
    },
    {
     "t": 5.0,
     "y": 2.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 5.0,
    "label": "s = 25.0 m"
   }
  }
 },
 "kin-2.9-q14": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 5.0,
     "y": 30
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 5.0,
    "label": "s = 75.0 m"
   }
  }
 },
 "kin-2.9-q15": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 3.0,
     "y": 4
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 3.0,
    "label": "s = 21.0 m"
   }
  }
 },
 "kin-2.9-q17": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 7.0
    },
    {
     "t": 4.0,
     "y": 19.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 4.0,
    "label": "s = 52.0 m"
   }
  }
 },
 "kin-2.9-q18": {
  "kind": "table",
  "props": {
   "headers": [
    "Object",
    "u / m/s",
    "a / m/s²",
    "t / s"
   ],
   "rows": [
    [
     "A",
     "0",
     "2.0",
     "10"
    ],
    [
     "B",
     "5.0",
     "0.50",
     "10"
    ],
    [
     "C",
     "10",
     "−1.0",
     "10"
    ]
   ]
  }
 },
 "kin-2.10-q2": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "1",
    "2",
    "3"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "5",
     "10",
     "15"
    ]
   ]
  }
 },
 "kin-2.10-q3": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "1",
    "2",
    "3"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "3",
     "8",
     "15"
    ]
   ]
  }
 },
 "kin-2.10-q5": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "2",
    "4",
    "6"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "8",
     "16",
     "24"
    ]
   ]
  }
 },
 "kin-2.10-q7": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "1",
    "2",
    "3",
    "4"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "2.0",
     "4.5",
     "8.0",
     "13"
    ]
   ]
  }
 },
 "kin-2.10-q9": {
  "kind": "table",
  "props": {
   "headers": [
    "Interval",
    "1",
    "2",
    "3",
    "4"
   ],
   "rows": [
    [
     "distance / cm",
     "2.0",
     "5.0",
     "8.0",
     "11"
    ]
   ]
  }
 },
 "kin-2.10-q11": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "1",
    "2",
    "3",
    "4"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "3",
     "7",
     "13",
     "21"
    ]
   ]
  }
 },
 "kin-2.10-q13": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 2.9,
     "y": 9.5
    },
    {
     "t": 3.1,
     "y": 10.5
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.10-q14": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "2",
     "4",
     "6",
     "8",
     "10"
    ]
   ]
  }
 },
 "kin-2.10-q15": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "1",
    "2",
    "3"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "4",
     "9",
     "16"
    ]
   ]
  }
 },
 "kin-2.10-q16": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 2.0,
     "y": 3.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.10-q17": {
  "kind": "table",
  "props": {
   "headers": [
    "Interval",
    "1",
    "2",
    "3",
    "4",
    "5"
   ],
   "rows": [
    [
     "distance / cm",
     "1.0",
     "1.6",
     "2.2",
     "2.8",
     "3.4"
    ]
   ]
  }
 },
 "kin-2.10-q18": {
  "kind": "table",
  "props": {
   "headers": [
    "Interval",
    "1",
    "2",
    "3",
    "4"
   ],
   "rows": [
    [
     "distance / cm",
     "1.0",
     "1.6",
     "2.5",
     "3.9"
    ]
   ]
  }
 },
 "kin-2.10-q20": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 4.0
    },
    {
     "t": 1.0,
     "y": 7.0
    },
    {
     "t": 2.0,
     "y": 5.0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.11-f2": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 0
    },
    {
     "t": 2.0,
     "y": 19.62
    }
   ],
   "xLabel": "time",
   "yLabel": "speed",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.11-f3": {
  "kind": "balldrop",
  "props": {
   "heights": [
    44.145
   ]
  }
 },
 "kin-2.11-q7": {
  "kind": "balldrop",
  "props": {
   "heights": [
    20
   ]
  }
 },
 "kin-2.11-q9": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 5.0
    },
    {
     "t": 2.0,
     "y": 24.62
    }
   ],
   "xLabel": "time",
   "yLabel": "speed",
   "xUnit": "s",
   "yUnit": "m/s"
  }
 },
 "kin-2.11-q10": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 1.019367991845056,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ]
  }
 },
 "kin-2.11-q12": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 10
    },
    {
     "t": 1.019367991845056,
     "y": 0
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "shade": {
    "t0": 0,
    "t1": 1.019367991845056,
    "label": "h = 5.10 m"
   }
  }
 },
 "kin-2.11-q14": {
  "kind": "balldrop",
  "props": {
   "heights": [
    50,
    100
   ]
  }
 },
 "kin-2.11-q15": {
  "kind": "motion",
  "props": {
   "kind": "velocity",
   "points": [
    {
     "t": 0,
     "y": 15
    },
    {
     "t": 1.529051987767584,
     "y": 0
    },
    {
     "t": 4.061930182366808,
     "y": -24.847535089018393
    }
   ],
   "xLabel": "time",
   "yLabel": "velocity",
   "xUnit": "s",
   "yUnit": "m/s",
   "hRefLines": [
    0
   ]
  }
 },
 "kin-2.11-q16": {
  "kind": "balldrop",
  "props": {
   "heights": [
    1.22625,
    4.905
   ]
  }
 },
 "kin-2.11-q17": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0",
    "2",
    "4",
    "6",
    "8"
   ],
   "rows": [
    [
     "v / m/s",
     "0",
     "19.4",
     "36.9",
     "47.8",
     "53.0"
    ]
   ]
  }
 },
 "kin-2.12-f2": {
  "kind": "balldrop",
  "props": {
   "heights": [
    2.0
   ]
  }
 },
 "kin-2.12-q11": {
  "kind": "table",
  "props": {
   "headers": [
    "Reading",
    "1",
    "2",
    "3",
    "4",
    "5"
   ],
   "rows": [
    [
     "t / s",
     "0.640",
     "0.638",
     "0.642",
     "0.639",
     "0.641"
    ]
   ]
  }
 },
 "kin-2.12-q14": {
  "kind": "table",
  "props": {
   "headers": [
    "t² / s²",
    "0.10",
    "0.20",
    "0.30",
    "0.40",
    "0.50"
   ],
   "rows": [
    [
     "s / m",
     "0.49",
     "0.98",
     "1.47",
     "1.96",
     "2.45"
    ]
   ]
  }
 },
 "kin-2.12-q18": {
  "kind": "balldrop",
  "props": {
   "heights": [
    1.99,
    2.0
   ]
  }
 },
 "kin-2.13-f2": {
  "kind": "projectile",
  "props": {
   "u": 15,
   "angleDeg": 0,
   "launchHeight": 1.0,
   "showLaunchComponents": false
  }
 },
 "kin-2.13-f6": {
  "kind": "projectile",
  "props": {
   "u": 8.0,
   "angleDeg": 0,
   "launchHeight": 1.22625,
   "showLaunchComponents": false
  }
 },
 "kin-2.13-q7": {
  "kind": "vector",
  "props": {
   "vectors": [
    {
     "magnitude": 20,
     "angleDeg": 30,
     "label": "20 m/s"
    }
   ],
   "mode": "fromOrigin"
  }
 },
 "kin-2.13-q11": {
  "kind": "projectile",
  "props": {
   "u": 20,
   "angleDeg": 30
  }
 },
 "kin-2.13-q14": {
  "kind": "projectile",
  "props": {
   "u": 4.0,
   "angleDeg": 0,
   "launchHeight": 0.9
  }
 },
 "kin-2.13-q15": {
  "kind": "projectile",
  "props": {
   "u": 25,
   "angleDeg": 40,
   "launchHeight": 15
  }
 },
 "kin-2.13-q16": {
  "kind": "projectile",
  "props": {
   "u": 20.434856444799117,
   "angleDeg": 35
  }
 },
 "kin-2.13-q17": {
  "kind": "table",
  "props": {
   "headers": [
    "t / s",
    "0.10",
    "0.30"
   ],
   "rows": [
    [
     "x / m",
     "2.0",
     "6.0"
    ]
   ]
  }
 },
 "kin-2.13-q18": {
  "kind": "projectile",
  "props": {
   "u": 18.0,
   "angleDeg": 0,
   "launchHeight": 30.65625
  }
 },
 "kin-2.13-q20": {
  "kind": "projectile",
  "props": {
   "u": 60,
   "angleDeg": 0,
   "launchHeight": 80
  }
 },
 "kin-2.14-q7": {
  "kind": "projectile",
  "props": {
   "u": 30,
   "angleDeg": 25
  }
 },
 "kin-2.14-q14": {
  "kind": "projectile",
  "props": {
   "u": 20,
   "angleDeg": 35
  }
 },
 "kin-2.14-q15": {
  "kind": "projectile",
  "props": {
   "u": 25,
   "angleDeg": 40
  }
 },
 "kin-2.14-q16": {
  "kind": "projectile",
  "props": {
   "u": 20.030240230683518,
   "angleDeg": 50
  }
 },
 "kin-2.14-q17": {
  "kind": "table",
  "props": {
   "headers": [
    "Angle",
    "20°",
    "45°",
    "70°"
   ],
   "rows": [
    [
     "Range / m",
     "14.7",
     "22.9",
     "14.7"
    ]
   ]
  }
 },
 "kin-2.14-q18": {
  "kind": "projectile",
  "props": {
   "u": 24,
   "angleDeg": 28,
   "launchHeight": 1.8
  }
 },
 "kin-2.14-q20": {
  "kind": "projectile",
  "props": {
   "u": 30,
   "angleDeg": 40,
   "launchHeight": 2.0
  }
 }
};
